export const FALLBACK_GAME = {
    game_title_es: "Quien quiere ser ISOmillonario (reserva)",
    game_title_en: "Who wants to be ISOmillionaire (fallback)",
    iso_focus: ["ISO 9241", "ISO/IEC/IEEE 29148", "ISO/IEC 25010:2023"],
    questions: [
        {
            id: "q1",
            level: 1,
            amount: 100,
            iso_standard: "ISO 9241",
            context_es: "Una app bancaria oculta el botón de transferencias en un menú poco visible.",
            context_en: "A banking app hides the transfer button in a barely visible menu.",
            question_es: "¿Qué atributo de ISO 9241 se ve más afectado?",
            question_en: "Which ISO 9241 attribute is most impacted?",
            options_es: ["Seguridad", "Eficiencia", "Detectabilidad", "Portabilidad"],
            options_en: ["Security", "Efficiency", "Findability", "Portability"],
            correct_index: 2,
            option_difficulty: ["easy", "medium", "easy", "hard"],
            hint_es: "Piensa en la facilidad para localizar elementos.",
            hint_en: "Think about how easy it is to locate elements.",
            friend_answer_es: "Yo elegiría detectabilidad, es difícil encontrarlo.",
            friend_answer_en: "I'd pick findability; it's hard to find.",
            friend_confidence: "high"
        },
        {
            id: "q2",
            level: 2,
            amount: 200,
            iso_standard: "ISO/IEC/IEEE 29148",
            context_es: "El documento de requisitos mezcla reglas de negocio y UI en el mismo apartado.",
            context_en: "The requirements document mixes business rules and UI in the same section.",
            question_es: "¿Qué principio de ISO 29148 se incumple?",
            question_en: "Which ISO 29148 principle is violated?",
            options_es: ["Verificabilidad", "Clasificación lógica", "Trazabilidad", "Consistencia"],
            options_en: ["Verifiability", "Logical structuring", "Traceability", "Consistency"],
            correct_index: 1,
            option_difficulty: ["medium", "easy", "hard", "medium"],
            hint_es: "Piensa en la organización clara de requisitos.",
            hint_en: "Consider clear organization of requirements.",
            friend_answer_es: "Yo apostaría por clasificación lógica.",
            friend_answer_en: "I'd go with logical structuring.",
            friend_confidence: "medium"
        },
        {
            id: "q3",
            level: 3,
            amount: 300,
            iso_standard: "ISO/IEC 25010:2023",
            context_es: "Un sistema POS funciona rápido pero falla con frecuencia en horas pico.",
            context_en: "A POS system is fast but frequently fails during peak hours.",
            question_es: "¿Qué característica de calidad se afecta más?",
            question_en: "Which quality characteristic is most affected?",
            options_es: ["Confiabilidad", "Usabilidad", "Compatibilidad", "Seguridad"],
            options_en: ["Reliability", "Usability", "Compatibility", "Security"],
            correct_index: 0,
            option_difficulty: ["easy", "medium", "hard", "hard"],
            hint_es: "Piensa en disponibilidad y tolerancia a fallos.",
            hint_en: "Think about availability and fault tolerance.",
            friend_answer_es: "Confiabilidad, porque falla en momentos críticos.",
            friend_answer_en: "Reliability, since it fails at critical times.",
            friend_confidence: "high"
        },
        {
            id: "q4",
            level: 4,
            amount: 500,
            iso_standard: "ISO 9241",
            context_es: "Usuarios novatos se pierden porque los iconos no describen su función.",
            context_en: "Novice users get lost because icons do not describe their function.",
            question_es: "¿Qué principio de ISO 9241 se viola?",
            question_en: "Which ISO 9241 principle is violated?",
            options_es: ["Adecuación a la tarea", "Autodescriptivo", "Flexibilidad", "Error defensivo"],
            options_en: ["Suitability for the task", "Self-descriptiveness", "Flexibility", "Error tolerance"],
            correct_index: 1,
            option_difficulty: ["medium", "easy", "hard", "medium"],
            hint_es: "El sistema debería explicarse por sí mismo.",
            hint_en: "The system should explain itself.",
            friend_answer_es: "Autodescriptivo, seguro.",
            friend_answer_en: "Self-descriptiveness, for sure.",
            friend_confidence: "high"
        },
        {
            id: "q5",
            level: 5,
            amount: 1000,
            iso_standard: "ISO/IEC/IEEE 29148",
            context_es: "Los requisitos usan verbos ambiguos como 'optimizar'.",
            context_en: "Requirements use ambiguous verbs like 'optimize'.",
            question_es: "¿Qué atributo de calidad falta?",
            question_en: "Which quality attribute is missing?",
            options_es: ["Realizables", "Completos", "Medibles", "Compatibles"],
            options_en: ["Feasible", "Complete", "Measurable", "Compatible"],
            correct_index: 2,
            option_difficulty: ["medium", "medium", "easy", "hard"],
            hint_es: "Se necesita un objetivo cuantificable.",
            hint_en: "A quantifiable goal is needed.",
            friend_answer_es: "Diría medibles.",
            friend_answer_en: "I'd say measurable.",
            friend_confidence: "medium"
        },
        {
            id: "q6",
            level: 6,
            amount: 2000,
            iso_standard: "ISO/IEC 25010:2023",
            context_es: "Un portal educativo funciona en Chrome pero no en Safari.",
            context_en: "An education portal works in Chrome but not Safari.",
            question_es: "¿Qué subcaracterística está en riesgo?",
            question_en: "Which sub-characteristic is at risk?",
            options_es: ["Compatibilidad co-existencia", "Portabilidad adaptabilidad", "Usabilidad accesibilidad", "Seguridad confidencialidad"],
            options_en: ["Compatibility co-existence", "Portability adaptability", "Usability accessibility", "Security confidentiality"],
            correct_index: 1,
            option_difficulty: ["medium", "easy", "medium", "hard"],
            hint_es: "Piensa en ejecutar en múltiples entornos.",
            hint_en: "Think about running on multiple environments.",
            friend_answer_es: "Adaptabilidad, claro.",
            friend_answer_en: "Adaptability, of course.",
            friend_confidence: "high"
        },
        {
            id: "q7",
            level: 7,
            amount: 4000,
            iso_standard: "ISO/IEC/IEEE 29148",
            context_es: "Los cambios de requisitos no guardan relación con sus historias originales.",
            context_en: "Requirement changes are not linked to their original stories.",
            question_es: "¿Qué atributo falta?",
            question_en: "Which attribute is missing?",
            options_es: ["Trazabilidad", "Unicidad", "Verificabilidad", "Testabilidad"],
            options_en: ["Traceability", "Uniqueness", "Verifiability", "Testability"],
            correct_index: 0,
            option_difficulty: ["easy", "medium", "hard", "medium"],
            hint_es: "Debe seguirse el rastro del requisito.",
            hint_en: "One must follow the requirement trail.",
            friend_answer_es: "Trazabilidad me suena correcto.",
            friend_answer_en: "Traceability sounds right.",
            friend_confidence: "high"
        },
        {
            id: "q8",
            level: 8,
            amount: 8000,
            iso_standard: "ISO 9241",
            context_es: "Un chatbot obliga a reescribir datos tras cada error.",
            context_en: "A chatbot forces users to retype data after each error.",
            question_es: "¿Qué principio falta?",
            question_en: "Which principle is missing?",
            options_es: ["Recuperación de errores", "Control del usuario", "Conformidad con expectativas", "Compatibilidad"],
            options_en: ["Error recovery", "User control", "Conformity with expectations", "Compatibility"],
            correct_index: 0,
            option_difficulty: ["easy", "medium", "medium", "hard"],
            hint_es: "Piensa en ayudar tras equivocarse.",
            hint_en: "Think about helping after mistakes.",
            friend_answer_es: "Recuperación, sin duda.",
            friend_answer_en: "Recovery, no doubt.",
            friend_confidence: "high"
        },
        {
            id: "q9",
            level: 9,
            amount: 16000,
            iso_standard: "ISO/IEC 25010:2023",
            context_es: "Un motor de IA agrega nuevas funciones sin documentos de instalación claros.",
            context_en: "An AI engine adds new features without clear installation docs.",
            question_es: "¿Qué subcaracterística afecta?",
            question_en: "Which sub-characteristic is affected?",
            options_es: ["Mantenibilidad modularidad", "Portabilidad instalabilidad", "Usabilidad satisfacción", "Seguridad integridad"],
            options_en: ["Maintainability modularity", "Portability installability", "Usability satisfaction", "Security integrity"],
            correct_index: 1,
            option_difficulty: ["medium", "easy", "hard", "medium"],
            hint_es: "Facilidad para instalar en un entorno.",
            hint_en: "Ease of installing in an environment.",
            friend_answer_es: "Instalabilidad parece obvio.",
            friend_answer_en: "Installability seems obvious.",
            friend_confidence: "high"
        },
        {
            id: "q10",
            level: 10,
            amount: 32000,
            iso_standard: "ISO/IEC/IEEE 29148",
            context_es: "El equipo describe requisitos con pronombres ambiguos como 'ellos'.",
            context_en: "Team describes requirements with ambiguous pronouns like 'they'.",
            question_es: "¿Qué característica se compromete?",
            question_en: "Which characteristic is compromised?",
            options_es: ["Claridad", "Consistencia", "Rastreabilidad", "Viabilidad"],
            options_en: ["Clarity", "Consistency", "Traceability", "Feasibility"],
            correct_index: 0,
            option_difficulty: ["easy", "medium", "hard", "medium"],
            hint_es: "La redacción debe ser inequívoca.",
            hint_en: "Wording must be unambiguous.",
            friend_answer_es: "Claridad es clave.",
            friend_answer_en: "Clarity is key.",
            friend_confidence: "high"
        },
        {
            id: "q11",
            level: 11,
            amount: 64000,
            iso_standard: "ISO/IEC 25010:2023",
            context_es: "Un microservicio se despliega rápido pero su código es difícil de reutilizar.",
            context_en: "A microservice deploys quickly but code is hard to reuse.",
            question_es: "¿Qué característica se ve afectada?",
            question_en: "Which characteristic is affected?",
            options_es: ["Mantenibilidad reutilización", "Rendimiento", "Seguridad autenticación", "Compatibilidad interoperabilidad"],
            options_en: ["Maintainability reusability", "Performance", "Security authentication", "Compatibility interoperability"],
            correct_index: 0,
            option_difficulty: ["easy", "hard", "medium", "medium"],
            hint_es: "Piensa en replicar componentes.",
            hint_en: "Think about replicating components.",
            friend_answer_es: "Reutilización claramente.",
            friend_answer_en: "Reusability clearly.",
            friend_confidence: "medium"
        },
        {
            id: "q12",
            level: 12,
            amount: 125000,
            iso_standard: "ISO 9241",
            context_es: "Una consola industrial bloquea la entrada tras tres errores.",
            context_en: "An industrial console locks input after three mistakes.",
            question_es: "¿Qué principio de usabilidad se afecta?",
            question_en: "Which usability principle is impacted?",
            options_es: ["Control del usuario", "Prevención de errores", "Adecuación al contexto", "Compatibilidad"],
            options_en: ["User control", "Error prevention", "Suitability for context", "Compatibility"],
            correct_index: 0,
            option_difficulty: ["easy", "medium", "hard", "medium"],
            hint_es: "El usuario debe sentirse al mando.",
            hint_en: "Users should feel in control.",
            friend_answer_es: "Control del usuario, pienso.",
            friend_answer_en: "User control, I think.",
            friend_confidence: "medium"
        },
        {
            id: "q13",
            level: 13,
            amount: 250000,
            iso_standard: "ISO/IEC/IEEE 29148",
            context_es: "Los requisitos funcionales no describen condiciones de éxito medibles.",
            context_en: "Functional requirements lack measurable success conditions.",
            question_es: "¿Qué atributo de calidad falta?",
            question_en: "Which quality attribute is missing?",
            options_es: ["Testabilidad", "No ambigüedad", "Consistencia", "Modularidad"],
            options_en: ["Testability", "Unambiguity", "Consistency", "Modularity"],
            correct_index: 0,
            option_difficulty: ["easy", "medium", "hard", "hard"],
            hint_es: "¿Puedes probar que se cumpla?",
            hint_en: "Can you test it is met?",
            friend_answer_es: "Testabilidad, sin duda.",
            friend_answer_en: "Testability, no doubt.",
            friend_confidence: "high"
        },
        {
            id: "q14",
            level: 14,
            amount: 500000,
            iso_standard: "ISO/IEC 25010:2023",
            context_es: "Una API cumple tiempos pero expone datos sensibles en logs.",
            context_en: "An API meets timing goals but exposes sensitive data in logs.",
            question_es: "¿Qué subcaracterística de calidad se compromete?",
            question_en: "Which quality sub-characteristic is compromised?",
            options_es: ["Seguridad confidencialidad", "Eficiencia temporal", "Protección ante errores", "Compatibilidad"],
            options_en: ["Security confidentiality", "Time efficiency", "Fault protection", "Compatibility"],
            correct_index: 0,
            option_difficulty: ["easy", "medium", "hard", "hard"],
            hint_es: "Los registros no deben filtrar secretos.",
            hint_en: "Logs must not leak secrets.",
            friend_answer_es: "Confidencialidad, clarísimo.",
            friend_answer_en: "Confidentiality, clearly.",
            friend_confidence: "high"
        },
        {
            id: "q15",
            level: 15,
            amount: 1000000,
            iso_standard: "ISO 9241",
            context_es: "Un ERP crítico obliga a usar combinaciones de teclas no documentadas.",
            context_en: "A critical ERP forces undocumented key combinations.",
            question_es: "¿Qué principio es el más grave?",
            question_en: "Which principle is most severely violated?",
            options_es: ["Conformidad con expectativas", "Flexibilidad", "Autodescriptivo", "Adecuación para aprendizaje"],
            options_en: ["Conformity with expectations", "Flexibility", "Self-descriptiveness", "Suitability for learning"],
            correct_index: 0,
            option_difficulty: ["medium", "hard", "medium", "hard"],
            hint_es: "Los usuarios esperan patrones conocidos.",
            hint_en: "Users expect familiar patterns.",
            friend_answer_es: "Conformidad, porque rompen patrones.",
            friend_answer_en: "Conformity, since patterns break.",
            friend_confidence: "medium"
        }
    ]
};
