const PREDEFINED_GAMES = [
    {
        game_id: "iso9241_focus",
        game_title_es: "Usabilidad centrada en ISO 9241",
        game_title_en: "ISO 9241 Usability Sprint",
        iso_focus: ["ISO 9241"],
        questions: [
            {
                id: "iso9241_q1",
                context_es: "Una intranet de RRHH muestra los formularios en un menú lateral sin iconos y los empleados tardan en ubicarlos.",
                context_en: "An HR intranet lists forms in a side menu without icons and employees take too long to find them.",
                question_es: "¿Qué principio ISO 9241-110 falla principalmente?",
                question_en: "Which ISO 9241-110 principle is primarily violated?",
                options_es: ["Control explícito", "Auto-descriptividad", "Conformidad con expectativas", "Tolerancia a errores"],
                options_en: ["Explicit control", "Self-descriptiveness", "Conformity with expectations", "Error tolerance"],
                correct_index: 1,
                explanation_es: "Los formularios no explican su contenido, por lo que falta auto-descriptividad.",
                explanation_en: "Users cannot infer purpose from the labels, so self-descriptiveness is missing.",
                iso_standard: "ISO 9241",
                difficulty: "easy"
            },
            {
                id: "iso9241_q2",
                context_es: "Una app móvil cambia de forma impredecible el orden de los filtros según la categoría seleccionada.",
                context_en: "A mobile app rearranges filter order unpredictably depending on the selected category.",
                question_es: "¿Qué aspecto de consistencia afecta esto en ISO 9241?",
                question_en: "Which consistency aspect does this break per ISO 9241?",
                options_es: ["Consistencia interna", "Consistencia externa", "Consistencia semántica", "Consistencia visual"],
                options_en: ["Internal consistency", "External consistency", "Semantic consistency", "Visual consistency"],
                correct_index: 0,
                explanation_es: "El comportamiento cambia dentro de la misma app, rompiendo la consistencia interna.",
                explanation_en: "Behavior varies inside the app, violating internal consistency.",
                iso_standard: "ISO 9241",
                difficulty: "medium"
            },
            {
                id: "iso9241_q3",
                context_es: "El asistente de instalación oculta el progreso real y sólo muestra animaciones genéricas.",
                context_en: "The installer hides actual progress and only shows generic animations.",
                question_es: "¿Qué atributo ISO 9241-112 debería priorizarse?",
                question_en: "Which ISO 9241-112 attribute should be prioritized?",
                options_es: ["Distinción", "Claridad", "Relevancia", "Concisión"],
                options_en: ["Discriminability", "Clarity", "Relevance", "Conciseness"],
                correct_index: 1,
                explanation_es: "El usuario necesita claridad para comprender el estado real.",
                explanation_en: "Users require clarity to understand real progress.",
                iso_standard: "ISO 9241",
                difficulty: "medium"
            },
            {
                id: "iso9241_q4",
                context_es: "En una sala de control, las alarmas aparecen con el mismo color que las notificaciones informativas.",
                context_en: "In a control room, alarms use the same color as informational notifications.",
                question_es: "¿Qué componente de la percepción se ve comprometido?",
                question_en: "Which perception component is compromised?",
                options_es: ["Codificación redundante", "Gestalt", "Relación figura-fondo", "Agrupación"],
                options_en: ["Redundant coding", "Gestalt", "Figure-ground", "Grouping"],
                correct_index: 0,
                explanation_es: "La falta de codificación redundante impide distinguir alarmas críticas.",
                explanation_en: "Without redundant coding, critical alarms cannot stand out.",
                iso_standard: "ISO 9241",
                difficulty: "hard"
            },
            {
                id: "iso9241_q5",
                context_es: "Un panel financiero muestra tablas densas sin separación y muchos usuarios cometen errores al editar celdas.",
                context_en: "A financial dashboard shows dense tables without spacing and users misclick editable cells.",
                question_es: "Según ISO 9241-125, ¿qué factor de diseño se debe reforzar?",
                question_en: "According to ISO 9241-125, which design factor needs reinforcement?",
                options_es: ["Compatibilidad", "Agrupación", "Retroalimentación", "Contraincidencias"],
                options_en: ["Compatibility", "Grouping", "Feedback", "Preventing coincidences"],
                correct_index: 1,
                explanation_es: "Agrupar y espaciar mejora la precisión en datos densos.",
                explanation_en: "Better grouping and spacing improves accuracy in dense tables.",
                iso_standard: "ISO 9241",
                difficulty: "medium"
            },
            {
                id: "iso9241_q6",
                context_es: "Una terminal de kiosco finaliza la compra sin confirmación final y los usuarios se sorprenden.",
                context_en: "A kiosk terminal finishes checkout without a final confirmation and users get surprised.",
                question_es: "¿Qué diálogo ISO 9241 debería incorporarse?",
                question_en: "Which ISO 9241 dialogue principle should be added?",
                options_es: ["Control explícito", "Adecuación a la tarea", "Prevención de errores", "Adaptabilidad"],
                options_en: ["Explicit control", "Task suitability", "Error prevention", "Adaptability"],
                correct_index: 0,
                explanation_es: "Confirmar antes de finalizar otorga control explícito al usuario.",
                explanation_en: "Confirming before finishing provides explicit control.",
                iso_standard: "ISO 9241",
                difficulty: "easy"
            }
        ]
    },
    {
        game_id: "iso29148_focus",
        game_title_es: "ISO 29148 - Taller de requisitos",
        game_title_en: "ISO 29148 Requirements Lab",
        iso_focus: ["ISO/IEC/IEEE 29148"],
        questions: [
            {
                id: "iso29148_q1",
                context_es: "Un backlog mezcla historias de usuario con requisitos regulatorios sin trazabilidad.",
                context_en: "A backlog mixes user stories with regulatory requirements without traceability.",
                question_es: "¿Qué disciplina ISO 29148 se debe reforzar?",
                question_en: "Which ISO 29148 discipline must be reinforced?",
                options_es: ["Planificación", "Gestión de configuración", "Trazabilidad", "Verificación"],
                options_en: ["Planning", "Configuration management", "Traceability", "Verification"],
                correct_index: 2,
                explanation_es: "La trazabilidad enlaza requisitos regulatorios con historias ejecutables.",
                explanation_en: "Traceability connects regulatory needs to executable stories.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "easy"
            },
            {
                id: "iso29148_q2",
                context_es: "El documento de requisitos no define criterios de aceptación cuantitativos.",
                context_en: "The requirements doc lacks quantitative acceptance criteria.",
                question_es: "¿Qué característica de calidad falta?",
                question_en: "Which requirement quality attribute is missing?",
                options_es: ["Comprensible", "Verificable", "Consistente", "Completa"],
                options_en: ["Understandable", "Verifiable", "Consistent", "Complete"],
                correct_index: 1,
                explanation_es: "Sin métricas no se puede verificar el cumplimiento.",
                explanation_en: "Without metrics the requirement cannot be verified.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "medium"
            },
            {
                id: "iso29148_q3",
                context_es: "El equipo recibe requisitos contradictorios de dos stakeholders clave.",
                context_en: "The team receives contradictory requirements from two key stakeholders.",
                question_es: "¿Qué actividad prioriza ISO 29148 para resolverlo?",
                question_en: "Which ISO 29148 activity helps resolve this?",
                options_es: ["Gestión de conflictos", "Revisión técnica", "Asignación de recursos", "Priorización MoSCoW"],
                options_en: ["Conflict management", "Technical review", "Resource allocation", "MoSCoW prioritization"],
                correct_index: 0,
                explanation_es: "Gestionar conflictos asegura acuerdos antes de formalizar requisitos.",
                explanation_en: "Conflict management ensures alignment before baselines.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "medium"
            },
            {
                id: "iso29148_q4",
                context_es: "El dossier de requisitos reutiliza fragmentos de proyectos previos sin contextualizar.",
                context_en: "The requirements dossier reuses fragments from past projects without context.",
                question_es: "¿Qué riesgo destaca ISO 29148?",
                question_en: "Which risk does ISO 29148 highlight?",
                options_es: ["Inconsistencia", "Sobrecostos", "Seguridad", "Rendimiento"],
                options_en: ["Inconsistency", "Cost overrun", "Security", "Performance"],
                correct_index: 0,
                explanation_es: "Copiar sin adaptar introduce contradicciones internas.",
                explanation_en: "Copying without tailoring introduces inconsistencies.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "hard"
            },
            {
                id: "iso29148_q5",
                context_es: "No existe una matriz que relacione requisitos con casos de prueba.",
                context_en: "No matrix relates requirements to test cases.",
                question_es: "¿Qué artefacto recomienda ISO 29148?",
                question_en: "Which artifact does ISO 29148 recommend?",
                options_es: ["Matriz de trazabilidad", "Matriz RACI", "Roadmap", "Work Breakdown"],
                options_en: ["Traceability matrix", "RACI matrix", "Roadmap", "Work Breakdown"],
                correct_index: 0,
                explanation_es: "La matriz de trazabilidad enlaza requisitos con verificación.",
                explanation_en: "Traceability matrices connect requirements to verification.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "easy"
            },
            {
                id: "iso29148_q6",
                context_es: "El comité de validación detecta requisitos ambiguos en la fase final.",
                context_en: "The validation board finds ambiguous requirements at the end stage.",
                question_es: "¿Qué práctica hubiera prevenido esto?",
                question_en: "Which practice could prevent this?",
                options_es: ["Revisión temprana", "Gestión del conocimiento", "Refinamiento ágil", "Gamificación"],
                options_en: ["Early review", "Knowledge management", "Agile refinement", "Gamification"],
                correct_index: 0,
                explanation_es: "Las revisiones tempranas identifican ambigüedades antes de validar.",
                explanation_en: "Early reviews surface ambiguities before validation.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "medium"
            }
        ]
    },
    {
        game_id: "iso25010_focus",
        game_title_es: "Calidad de producto ISO/IEC 25010",
        game_title_en: "ISO/IEC 25010 Product Quality",
        iso_focus: ["ISO/IEC 25010:2023"],
        questions: [
            {
                id: "iso25010_q1",
                context_es: "Un sistema de firma digital falla una vez por semana sin explicación clara.",
                context_en: "A digital signing system fails once a week without clear explanation.",
                question_es: "¿Qué característica ISO 25010 está comprometida?",
                question_en: "Which ISO 25010 characteristic is compromised?",
                options_es: ["Fiabilidad", "Compatibilidad", "Usabilidad", "Portabilidad"],
                options_en: ["Reliability", "Compatibility", "Usability", "Portability"],
                correct_index: 0,
                explanation_es: "Las fallas frecuentes afectan la fiabilidad.",
                explanation_en: "Frequent failures impact reliability.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "easy"
            },
            {
                id: "iso25010_q2",
                context_es: "La API tarda 4 segundos en responder a picos de carga moderados.",
                context_en: "The API takes 4 seconds to respond under moderate load spikes.",
                question_es: "¿Qué subcaracterística se debe optimizar?",
                question_en: "Which sub-characteristic should be optimized?",
                options_es: ["Capacidad de respuesta", "Protección contra errores", "Confidencialidad", "Reusabilidad"],
                options_en: ["Time behavior", "Error protection", "Confidentiality", "Reusability"],
                correct_index: 0,
                explanation_es: "El tiempo de respuesta forma parte del rendimiento.",
                explanation_en: "Time behavior belongs to performance efficiency.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "medium"
            },
            {
                id: "iso25010_q3",
                context_es: "Migrar el sistema a otro proveedor cloud requiere reescribir gran parte del código.",
                context_en: "Migrating the system to another cloud provider requires rewriting most code.",
                question_es: "¿Qué característica ISO 25010 debes revisar?",
                question_en: "Which ISO 25010 characteristic needs review?",
                options_es: ["Portabilidad", "Seguridad", "Compatibilidad", "Mantenibilidad"],
                options_en: ["Portability", "Security", "Compatibility", "Maintainability"],
                correct_index: 0,
                explanation_es: "La portabilidad cuida la capacidad de transferencia entre entornos.",
                explanation_en: "Portability addresses transfer between environments.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "medium"
            },
            {
                id: "iso25010_q4",
                context_es: "Una plataforma social comparte contraseñas en texto claro dentro de logs internos.",
                context_en: "A social platform stores passwords in clear text inside internal logs.",
                question_es: "¿Qué subcaracterística de seguridad se incumple?",
                question_en: "Which security sub-characteristic is violated?",
                options_es: ["Integridad", "Autenticidad", "No repudio", "Confidencialidad"],
                options_en: ["Integrity", "Authenticity", "Non-repudiation", "Confidentiality"],
                correct_index: 3,
                explanation_es: "Guardar contraseñas sin cifrar compromete la confidencialidad.",
                explanation_en: "Storing passwords in clear text breaks confidentiality.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "easy"
            },
            {
                id: "iso25010_q5",
                context_es: "El código tiene módulos duplicados y dificulta aplicar parches rápidos.",
                context_en: "Duplicate modules make it hard to patch quickly.",
                question_es: "¿Qué atributo de mantenibilidad debes priorizar?",
                question_en: "Which maintainability attribute must be prioritized?",
                options_es: ["Analizabilidad", "Modularidad", "Reusabilidad", "Modificabilidad"],
                options_en: ["Analyzability", "Modularity", "Reusability", "Modifiability"],
                correct_index: 1,
                explanation_es: "Una modularidad débil provoca duplicidades.",
                explanation_en: "Poor modularity creates duplication.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "medium"
            },
            {
                id: "iso25010_q6",
                context_es: "Usuarios con lectores de pantalla no pueden completar un flujo crítico.",
                context_en: "Screen reader users cannot finish a critical flow.",
                question_es: "¿Qué característica agregarías en la hoja de ruta?",
                question_en: "Which characteristic would you add to the roadmap?",
                options_es: ["Compatibilidad", "Usabilidad", "Fiabilidad", "Portabilidad"],
                options_en: ["Compatibility", "Usability", "Reliability", "Portability"],
                correct_index: 1,
                explanation_es: "La usabilidad incluye accesibilidad según ISO 25010.",
                explanation_en: "Usability covers accessibility per ISO 25010.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "easy"
            }
        ]
    },
    {
        game_id: "blended_quality",
        game_title_es: "Usabilidad vs Calidad técnica",
        game_title_en: "Usability vs Quality Trade-offs",
        iso_focus: ["ISO 9241", "ISO/IEC 25010:2023"],
        questions: [
            {
                id: "blend_q1",
                context_es: "Se agrega un tutorial animado que retrasa 3 segundos la pantalla de login empresarial.",
                context_en: "An animated tutorial delays an enterprise login screen by 3 seconds.",
                question_es: "¿Cómo equilibrar usabilidad y rendimiento?",
                question_en: "How should you balance usability and performance?",
                options_es: ["Eliminar el tutorial", "Mantenerlo sin cambios", "Hacerlo opcional y caché", "Moverlo a otra app"],
                options_en: ["Remove it", "Keep as is", "Make it optional and cached", "Move to another app"],
                correct_index: 2,
                explanation_es: "Permitir omitirlo y cachearlo preserva tiempo de respuesta y apoyo inicial.",
                explanation_en: "Optional + cached tutorial keeps time behavior and guidance.",
                iso_standard: "ISO 9241",
                difficulty: "medium"
            },
            {
                id: "blend_q2",
                context_es: "Un módulo crítico prioriza animaciones ricas y sacrifica contrastes mínimos.",
                context_en: "A critical module prioritizes rich animations and sacrifices minimum contrast.",
                question_es: "¿Qué debes priorizar según ISO 9241 e ISO 25010?",
                question_en: "What should you prioritize under ISO 9241 and ISO 25010?",
                options_es: ["Estética", "Seguridad", "Comprensibilidad", "Compatibilidad"],
                options_en: ["Aesthetics", "Security", "Comprehensibility", "Compatibility"],
                correct_index: 2,
                explanation_es: "La comprensibilidad visual garantiza accesibilidad y calidad de uso.",
                explanation_en: "Comprehensibility ensures accessible visual quality.",
                iso_standard: "ISO 9241",
                difficulty: "medium"
            },
            {
                id: "blend_q3",
                context_es: "Para acelerar el sistema, se deshabilitan validaciones server-side con impacto en integridad.",
                context_en: "To speed up the system, server-side validations are disabled affecting integrity.",
                question_es: "¿Qué característica ISO 25010 no debe sacrificarse?",
                question_en: "Which ISO 25010 characteristic must not be sacrificed?",
                options_es: ["Integridad", "Portabilidad", "Compatibilidad", "Usabilidad"],
                options_en: ["Integrity", "Portability", "Compatibility", "Usability"],
                correct_index: 0,
                explanation_es: "La integridad es esencial para datos confiables aun si implica más tiempo.",
                explanation_en: "Integrity keeps data trustworthy even if slower.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "hard"
            },
            {
                id: "blend_q4",
                context_es: "El equipo propone menús personalizables pero aumenta la complejidad de mantenimiento.",
                context_en: "The team proposes customizable menus but raises maintenance complexity.",
                question_es: "¿Cómo equilibrar adaptabilidad y mantenibilidad?",
                question_en: "How to balance adaptability and maintainability?",
                options_es: ["Permitir scripts libres", "Limitar plantillas aprobadas", "Eliminar personalización", "Delegar al usuario"],
                options_en: ["Allow free scripting", "Limit to approved templates", "Remove customization", "Delegate to user"],
                correct_index: 1,
                explanation_es: "Plantillas aprobadas brindan adaptabilidad controlada y mantenible.",
                explanation_en: "Approved templates provide controlled adaptability.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "medium"
            },
            {
                id: "blend_q5",
                context_es: "Una app IoT necesita reducir ancho de banda pero mantener feedback inmediato.",
                context_en: "An IoT app must cut bandwidth while keeping immediate feedback.",
                question_es: "¿Qué solución equilibra percepción y rendimiento?",
                question_en: "Which solution balances perception and performance?",
                options_es: ["Enviar todo en lote", "Usar indicadores locales y sincronizar", "Eliminar feedback", "Duplicar tráfico"],
                options_en: ["Batch everything", "Use local indicators + sync", "Remove feedback", "Double traffic"],
                correct_index: 1,
                explanation_es: "Indicadores locales mantienen percepción mientras se optimiza tráfico.",
                explanation_en: "Local indicators keep perception while optimizing traffic.",
                iso_standard: "ISO 9241",
                difficulty: "medium"
            },
            {
                id: "blend_q6",
                context_es: "El rediseño responsive rompe compatibilidad con navegadores corporativos.",
                context_en: "Responsive redesign breaks compatibility with corporate browsers.",
                question_es: "¿Qué acción recomienda ISO 25010?",
                question_en: "Which action does ISO 25010 recommend?",
                options_es: ["Descontinuar navegadores", "Plan de compatibilidad", "Ignorar feedback", "Migrar a app nativa"],
                options_en: ["Drop browsers", "Compatibility plan", "Ignore feedback", "Move to native app"],
                correct_index: 1,
                explanation_es: "Un plan de compatibilidad asegura funcionamiento en entornos objetivo.",
                explanation_en: "A compatibility plan ensures operation on target environments.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "easy"
            }
        ]
    },
    {
        game_id: "iso_mix_adv",
        game_title_es: "ISO avanzado mixto",
        game_title_en: "Advanced ISO Mix",
        iso_focus: ["ISO 9241", "ISO/IEC/IEEE 29148", "ISO/IEC 25010:2023"],
        questions: [
            {
                id: "mix_q1",
                context_es: "Una plataforma e-commerce planea lanzar en 4 países sin adaptar requisitos legales.",
                context_en: "An e-commerce platform plans four-country launch without adapting legal requirements.",
                question_es: "¿Qué combinación de normas aplicas primero?",
                question_en: "Which mix of standards do you apply first?",
                options_es: ["ISO 9241 + 25010", "ISO 29148 + 25010", "ISO 29148 + 9241", "Sólo ISO 9241"],
                options_en: ["ISO 9241 + 25010", "ISO 29148 + 25010", "ISO 29148 + 9241", "ISO 9241 only"],
                correct_index: 1,
                explanation_es: "Necesitas requisitos legales (29148) y calidad (25010) antes de UX.",
                explanation_en: "Legal requirements (29148) and quality attributes (25010) precede UX.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "hard"
            },
            {
                id: "mix_q2",
                context_es: "El chatbot de soporte confunde categorías por falta de datos en requisitos.",
                context_en: "The support chatbot confuses categories due to missing requirement data.",
                question_es: "¿Qué acción conjunta ayuda?",
                question_en: "Which combined action helps?",
                options_es: ["Sesiones de validación + test de usabilidad", "Más animaciones", "Escalar infraestructura", "Reducir idiomas"],
                options_en: ["Validation workshops + usability test", "More animations", "Scale infrastructure", "Reduce languages"],
                correct_index: 0,
                explanation_es: "Validar requisitos y medir usabilidad corrige categorías erróneas.",
                explanation_en: "Validating requirements and usability fixes wrong categories.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "medium"
            },
            {
                id: "mix_q3",
                context_es: "Una app de mantenimiento industrial necesita operar offline y sincronizar después.",
                context_en: "An industrial maintenance app must operate offline and sync later.",
                question_es: "¿Qué característica ISO 25010 aseguras junto con 9241?",
                question_en: "Which ISO 25010 characteristic do you ensure along ISO 9241?",
                options_es: ["Portabilidad", "Fiabilidad (madurez)", "Compatibilidad", "Seguridad"],
                options_en: ["Portability", "Reliability (maturity)", "Compatibility", "Security"],
                correct_index: 1,
                explanation_es: "La madurez y disponibilidad cubren funcionamiento offline confiable.",
                explanation_en: "Reliability maturity plus availability cover offline operation.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "medium"
            },
            {
                id: "mix_q4",
                context_es: "Los stakeholders piden métricas de experiencia y cumplimiento en el mismo dashboard.",
                context_en: "Stakeholders want experience and compliance metrics on one dashboard.",
                question_es: "¿Qué práctica combina ISO 9241 y 29148?",
                question_en: "Which practice combines ISO 9241 and 29148?",
                options_es: ["Historias de usuario con criterios de UX",
                    "Reescritura técnica",
                    "Diseño sólo en inglés",
                    "Monitorizar CPU"],
                options_en: ["User stories with UX criteria", "Technical rewrite", "English-only design", "Monitor CPU"],
                correct_index: 0,
                explanation_es: "Historias con criterios de UX trazables conectan experiencia y requisitos.",
                explanation_en: "User stories with UX acceptance criteria link experience and requirements.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "medium"
            },
            {
                id: "mix_q5",
                context_es: "La integración con proveedores externos genera errores intermitentes no detectados.",
                context_en: "Integration with external vendors produces undetected intermittent errors.",
                question_es: "¿Qué triada ISO aplicas?",
                question_en: "Which ISO triad do you apply?",
                options_es: ["ISO 9241 + 29148 + portabilidad", "ISO 25010 (fiabilidad) + 29148 + 9241",
                    "Sólo ISO 9241", "ISO 29148 + accesibilidad"],
                options_en: ["ISO 9241 + 29148 + portability", "ISO 25010 (reliability) + 29148 + 9241", "ISO 9241 only", "ISO 29148 + accessibility"],
                correct_index: 1,
                explanation_es: "Requisitos claros y métricas de fiabilidad combinadas con UX permiten detectar errores.",
                explanation_en: "Clear requirements plus reliability metrics and UX highlight the faults.",
                iso_standard: "ISO/IEC 25010:2023",
                difficulty: "hard"
            },
            {
                id: "mix_q6",
                context_es: "Un portal bilingüe muestra traducciones pero los usuarios dudan del significado técnico.",
                context_en: "A bilingual portal translates text yet users doubt the technical meaning.",
                question_es: "¿Qué práctica ISO asegura consistencia terminológica?",
                question_en: "Which ISO practice ensures terminology consistency?",
                options_es: ["Glosario trazable", "Traducción automática", "Eliminar idioma", "Reducir requisitos"],
                options_en: ["Traceable glossary", "Automatic translation", "Remove language", "Reduce requirements"],
                correct_index: 0,
                explanation_es: "Un glosario trazable conecta requisitos y UI en ambos idiomas.",
                explanation_en: "A traceable glossary links requirements and UI in both languages.",
                iso_standard: "ISO/IEC/IEEE 29148",
                difficulty: "medium"
            }
        ]
    }
];

if (typeof window !== "undefined") {
    window.PREDEFINED_GAMES = PREDEFINED_GAMES;
}

if (typeof module !== "undefined" && module.exports) {
    module.exports = { PREDEFINED_GAMES };
}
